name: derma_ai
description: Skin Disease Detection App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  percent_indicator: ^4.2.2
  image_cropper: ^3.0.1
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  http: ^0.13.5
  flutter_image_compress: ^1.1.3
  flutter_offline: ^2.1.0
  pdf: ^3.8.4
  open_filex: ^4.3.1
  printing: ^5.9.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/diseases/

  fonts:
    - family: Sora
      fonts:
        - asset: fonts/Sora-Regular.ttf
        - asset: fonts/Sora-SemiBold.ttf

    - family: LeckerliOne
      fonts:
        - asset: fonts/LeckerliOne-Regular.ttf
